# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Play Time' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!
  

  # Pods for Play Time
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  #pod 'PTFramework', :path => '/Users/bgouws/Desktop/PlayTimeRedux/PlayTime/Play Time/PTFramework'
  pod 'PTFramework', :git => 'https://github.com/bgouws/PTPod.git'

  target 'Play TimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
