# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Play Time' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!
  
  # Pods for Play Time
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Crashlytics'
  pod 'Fabric'
  pod 'Firebase/Performance'
  pod 'SkeletonView', '~> 1.8.7'

  pod 'PTFramework', :git => 'https://github.com/bgouws/PTPod.git'
  #pod 'PTFramework', :path => '/Users/bgouws/Desktop/PTFramework/PTPod'

  target 'Play TimeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OHHTTPStubs/Swift'
  end

end
