# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Play Time' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!
  

  # Pods for Play Time
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'Play TimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
